import type { Alert, Farm, Field, MarketQuote, Recommendation, UserProfile, UserSettings, WeatherSnapshot } from '../types'

export const demoUser: UserProfile = {
  id: 'demo-user',
  name: 'João Silva',
  email: 'joao.silva@email.com.br',
  initials: 'JS',
  farmName: 'Fazenda Boa Vista',
}

export const demoFarm: Farm = {
  id: 'farm-boa-vista',
  name: 'Fazenda Boa Vista',
  locality: 'Linhares',
  localityKind: 'municipio',
  municipality: 'Linhares',
  state: 'ES',
  locationLabel: 'Linhares, ES',
  productionType: 'Café Conilon',
  areaHa: 120,
  timezone: 'America/Sao_Paulo',
  coordinates: {
    latitude: -19.3947,
    longitude: -40.0643,
    accuracyM: 2500,
    source: 'manual',
    updatedAt: new Date().toISOString(),
  },
  notes: 'Áreas de soja e milho com pivô central no Talhão Norte.',
}

export const demoFields: Field[] = [
  {
    id: 'norte',
    name: 'Talhão Norte',
    crop: 'Soja',
    areaHa: 120,
    stage: 'R3 · enchimento',
    soilType: 'Argiloso',
    irrigation: 'Pivô central',
    climateStatus: 'Chuva provável nas próximas 6h',
    currentRecommendation: 'Adiar irrigação para amanhã',
    riskLevel: 'alto',
    lastUpdate: 'há 4 min',
    rainGaugeMm: 12,
    sensitivities: ['seca', 'excesso de chuva', 'vento'],
    coordinates: {
      latitude: -12.5299,
      longitude: -55.7142,
      accuracyM: 40,
      source: 'manual',
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'sul',
    name: 'Talhão Sul',
    crop: 'Milho',
    areaHa: 85,
    stage: 'V8 · vegetativo',
    soilType: 'Médio',
    irrigation: 'Sequeiro',
    climateStatus: 'Solo úmido, vento moderado',
    currentRecommendation: 'Monitorar pulverização',
    riskLevel: 'moderado',
    lastUpdate: 'há 12 min',
    rainGaugeMm: 8,
    sensitivities: ['vento', 'baixa umidade'],
    coordinates: {
      latitude: -12.556,
      longitude: -55.734,
      accuracyM: 45,
      source: 'manual',
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'leste',
    name: 'Várzea Leste',
    crop: 'Soja',
    areaHa: 60,
    stage: 'V5 · vegetativo',
    soilType: 'Arenoso',
    irrigation: 'Aspersão',
    climateStatus: 'Sem evento crítico',
    currentRecommendation: 'Janela aberta após 17h',
    riskLevel: 'baixo',
    lastUpdate: 'há 18 min',
    sensitivities: ['seca', 'geada'],
    coordinates: {
      latitude: -12.546,
      longitude: -55.691,
      accuracyM: 60,
      source: 'manual',
      updatedAt: new Date().toISOString(),
    },
  },
]

export const demoWeather: WeatherSnapshot = {
  fieldName: 'Talhão Norte',
  crop: 'Soja',
  stage: 'R3',
  location: 'Sorriso, MT',
  updatedAtLabel: 'atualizado há 4 min',
  current: {
    temperatureC: 27,
    description: 'Parcialmente nublado',
    feelsLikeC: 29,
    rainNext6h: '8–14 mm',
    wind: '12 km/h NE',
    humidity: '68%',
    minMax: '19° · 30°',
  },
  et0: {
    valueMm: 3.2,
    description: 'Demanda hídrica moderada. Solo úmido em 35 cm.',
    bars: [38, 52, 56, 62, 88, 45, 55],
  },
  irrigationWindow: {
    title: 'Amanhã, 05:00–08:30',
    description: 'Vento baixo · sem chuva prevista · solo receptivo.',
    progressPct: 46,
  },
  sources: [
    { name: 'Open-Meteo', value: '11 mm', detail: 'modelo global' },
    { name: 'RainViewer', value: 'ativo', detail: 'radar em aproximação' },
    { name: 'INMET', value: '9 mm', detail: 'estação próxima 18 km' },
  ],
}

export const demoRecommendations: Recommendation[] = [
  {
    id: 'rec-irrigacao-norte',
    kind: 'irrigacao',
    title: 'Adiar irrigação para amanhã pela manhã',
    description: 'Chuva prevista de 8–14 mm nas próximas 6h. ET₀ de hoje em 3.2 mm, abaixo da necessidade da soja em R3.',
    action: 'Aplicar à programação',
    justification: 'Chuva de 8–14 mm prevista nas próximas 6h e ET₀ estimada em 3.2 mm.',
    confidence: 92,
    sources: ['Previsão', 'Radar', 'Feedback local'],
    severity: 'alto',
    fieldId: 'norte',
    fieldName: 'Talhão Norte',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rec-pulverizacao-sul',
    kind: 'pulverizacao',
    title: 'Evitar pulverização amanhã cedo',
    description: 'Rajadas previstas acima de 22 km/h reduzem qualidade da aplicação foliar.',
    action: 'Reprogramar janela',
    justification: 'Vento acima da faixa ideal entre 06h e 10h.',
    confidence: 84,
    sources: ['Previsão', 'INMET'],
    severity: 'moderado',
    fieldId: 'sul',
    fieldName: 'Talhão Sul',
    updatedAt: new Date().toISOString(),
  },
]

export const demoAlerts: Alert[] = [
  {
    id: 'alert-rain',
    type: 'chuva severa',
    severity: 'alto',
    title: 'Chuva severa prevista',
    message: 'Acumulado de 35–50 mm previsto para Talhão Norte entre 18h e 23h.',
    fieldId: 'norte',
    fieldName: 'Talhão Norte',
    timeLabel: 'em 4h',
  },
  {
    id: 'alert-wind',
    type: 'vento forte',
    severity: 'moderado',
    title: 'Vento forte na janela de aplicação',
    message: 'Rajadas de 22 km/h previstas amanhã pela manhã. Evite pulverização foliar.',
    fieldId: 'sul',
    fieldName: 'Talhão Sul',
    timeLabel: 'amanhã 06h',
  },
  {
    id: 'alert-frost',
    type: 'geada',
    severity: 'baixo',
    title: 'Possibilidade remota de geada',
    message: 'Temperatura mínima de 4°C prevista para sexta. Monitorar.',
    fieldId: 'leste',
    fieldName: 'Várzea Leste',
    timeLabel: 'em 3 dias',
  },
]

export const demoQuotes: MarketQuote[] = [
  {
    id: 'soja',
    crop: 'Soja',
    region: 'Sorriso, MT',
    price: 'R$ 134,20',
    unit: '/sc 60kg',
    variationPct: 1.8,
    trend: 'up',
    history: [126, 128, 127, 131, 130, 132, 134],
    source: 'Watchlist local',
    updatedAt: new Date().toISOString(),
    volumeLabel: 'base balcão',
    basisLabel: '+R$ 2,10 vs semana',
  },
  {
    id: 'milho',
    crop: 'Milho',
    region: 'Sorriso, MT',
    price: 'R$ 62,80',
    unit: '/sc 60kg',
    variationPct: -0.6,
    trend: 'down',
    history: [65, 64, 64, 63, 62, 63, 62.8],
    source: 'Watchlist local',
    updatedAt: new Date().toISOString(),
    volumeLabel: 'mercado físico',
    basisLabel: '-R$ 0,40 hoje',
  },
  {
    id: 'algodao',
    crop: 'Algodão',
    region: 'Rondonópolis, MT',
    price: 'R$ 152,40',
    unit: '/@',
    variationPct: 2.4,
    trend: 'up',
    history: [144, 145, 147, 149, 148, 151, 152.4],
    source: 'Watchlist local',
    updatedAt: new Date().toISOString(),
    volumeLabel: 'pluma',
    basisLabel: '+2,4%',
  },
  {
    id: 'cafe',
    crop: 'Café',
    region: 'Patrocínio, MG',
    price: 'R$ 1.820,00',
    unit: '/sc 60kg',
    variationPct: 0.3,
    trend: 'up',
    history: [1780, 1795, 1802, 1810, 1804, 1816, 1820],
    source: 'Watchlist local',
    updatedAt: new Date().toISOString(),
    volumeLabel: 'arábica',
    basisLabel: 'estável',
  },
]

export const demoSettings: UserSettings = {
  autoLocationRefresh: false,
  dailySummary: true,
  dataSaverMode: false,
  metricSystem: true,
  marketReferencePrices: true,
  marketWatchlistOnly: false,
  twentyFourHour: true,
  pushNotifications: true,
  severeWeatherAlerts: true,
  offlineMode: true,
}
