export const APP_NAME = 'NimbuES'
export const APP_SLOGAN = 'Inteligência climática para proteger sua safra'
export const APP_VERSION = '1.0.0'
export const APP_STATE = 'ES'
export const APP_STATE_NAME = 'Espírito Santo'
